# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "demo-review"
client_id = "074f9f986df7efe6db4c9348f6f9364f"
application_url = "https://2536-103-163-248-146.ngrok-free.app"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://2536-103-163-248-146.ngrok-free.app/auth/callback",
  "https://2536-103-163-248-146.ngrok-free.app/auth/shopify/callback",
  "https://2536-103-163-248-146.ngrok-free.app/api/auth/callback",
  "https://2536-103-163-248-146.ngrok-free.app/.shopify/graphiql/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-8a352090.myshopify.com"
